"""
9 Trading Prediction Agents + Judge  (v4 — Full Indicator Suite)
Signals: BUY_CALL | BUY_PUT | HOLD
New agents: Fear & Greed Agent (VIX/Put-Call/momentum) + Political/Trump Agent (Google News RSS)
Judge fires at 6/9 consensus (67% agreement required)
"""
import os
import math
import json
import numpy as np
import pandas as pd
import urllib.request
import xml.etree.ElementTree as ET
import html as html_lib
import logging
import time
from scipy.stats import norm

from indicators import (
    compute_all_indicators, score_indicators_to_direction,
    suggest_options, safe_float,
    compute_supertrend, compute_stochastic, compute_rsi, compute_vwap,
    compute_adx, compute_williams_r, compute_ichimoku, compute_fibonacci,
    compute_pivot_levels, detect_rsi_divergence,
)
from kelly import compute_position_size

# Per-stock historical track record (generated by auto_refresh.py / tests/compute_track_record.py)
_TRACK_RECORD: dict = {}
_tr_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "track_record.json")


def reload_track_record() -> dict:
    """Re-read track_record.json from disk into the in-memory cache.
    Called by the auto-refresh background task after regenerating the file."""
    global _TRACK_RECORD
    try:
        if os.path.exists(_tr_path):
            with open(_tr_path) as _f:
                _TRACK_RECORD = json.load(_f) or {}
        else:
            _TRACK_RECORD = {}
    except Exception:
        _TRACK_RECORD = {}
    return _TRACK_RECORD


reload_track_record()


def get_track_record(symbol: str) -> dict | None:
    """Return the model's historical hit-rate on this stock, or None if not tracked."""
    if not symbol or not _TRACK_RECORD:
        return None
    rec = (_TRACK_RECORD.get("per_stock") or {}).get(symbol.upper())
    if not rec or rec.get("hit_rate") is None or rec.get("signals", 0) < 3:
        return None
    hr = rec["hit_rate"]
    if hr >= 65:
        rating = "strong"; note = f"Model has been right {hr}% of the time on {symbol} (n={rec['signals']})."
    elif hr >= 55:
        rating = "good"; note = f"Model historically right {hr}% on {symbol} (n={rec['signals']})."
    elif hr >= 45:
        rating = "weak"; note = f"⚠️ Model only {hr}% on {symbol} historically (n={rec['signals']}) — coin-flip territory."
    else:
        rating = "poor"; note = f"⚠️ Model only {hr}% on {symbol} historically (n={rec['signals']}) — has been wrong more than right."
    return {"hit_rate": hr, "signals": rec["signals"], "rating": rating, "note": note}

logger = logging.getLogger(__name__)
Signal = str  # "BUY_CALL" | "BUY_PUT" | "HOLD"


def _vote(agent_name, emoji, signal, confidence, reason, **extra):
    return {"agent": agent_name, "emoji": emoji, "vote": signal,
            "confidence": round(min(confidence, 97), 1), "reason": reason, **extra}


def _hold(agent_name, emoji, reason):
    return {"agent": agent_name, "emoji": emoji, "vote": "HOLD",
            "confidence": 50.0, "reason": reason}


# ─────────────────────────────────────────────────────────────────────────────
# 1. PRICE ACTION AGENT
# ─────────────────────────────────────────────────────────────────────────────
class PriceActionAgent:
    name = "Price Action Agent"
    emoji = "🕯️"
    method = "Candles + SuperTrend + Pivots + Inside-bar/Key-reversal + BB squeeze + RS vs SPY"

    def analyze(self, df, ind):
        try:
            closes = df["Close"].values
            opens = df["Open"].values
            highs = df["High"].values
            lows = df["Low"].values
            n = len(closes)
            if n < 10:
                return _hold(self.name, self.emoji, "Insufficient data")

            c, o, h, l = closes[-1], opens[-1], highs[-1], lows[-1]
            pc, po = closes[-2], opens[-2]
            ph, pl = highs[-2], lows[-2]
            body = abs(c - o)
            rng = h - l
            bp = body / rng if rng > 0 else 0
            uw = (h - max(c, o)) / rng if rng > 0 else 0
            lw = (min(c, o) - l) / rng if rng > 0 else 0

            signals, reasons = [], []

            # Candlestick patterns
            if c > o and pc < po and c > po and o < pc:
                signals.append("BUY_CALL"); reasons.append("Bullish engulfing")
            if c < o and pc > po and c < po and o > pc:
                signals.append("BUY_PUT"); reasons.append("Bearish engulfing")
            if lw > 0.6 and uw < 0.1 and c >= o:
                signals.append("BUY_CALL"); reasons.append("Hammer reversal")
            if uw > 0.6 and lw < 0.1 and c <= o:
                signals.append("BUY_PUT"); reasons.append("Shooting star")
            if c > o and bp > 0.65 and ind.get("rel_volume", 1) > 1.3:
                signals.append("BUY_CALL"); reasons.append(f"Strong bull candle {ind.get('rel_volume',1):.1f}×vol")
            if c < o and bp > 0.65 and ind.get("rel_volume", 1) > 1.3:
                signals.append("BUY_PUT"); reasons.append(f"Strong bear candle {ind.get('rel_volume',1):.1f}×vol")

            # NEW: Inside-bar break (3-bar continuation pattern)
            # Yesterday's range was inside day-before's range; today breaks one side.
            if n >= 3:
                pph, ppl = highs[-3], lows[-3]
                inside_yesterday = (ph <= pph) and (pl >= ppl)
                if inside_yesterday:
                    if h > ph and c > ph:
                        signals.append("BUY_CALL"); reasons.append("Inside-bar break↑")
                    elif l < pl and c < pl:
                        signals.append("BUY_PUT"); reasons.append("Inside-bar break↓")

            # NEW: 3-bar key reversal (lower-low then strong close above prev high)
            if n >= 3 and l < lows[-2] and c > highs[-2]:
                signals.append("BUY_CALL"); reasons.append("3-bar bullish key reversal")
            if n >= 3 and h > highs[-2] and c < lows[-2]:
                signals.append("BUY_PUT"); reasons.append("3-bar bearish key reversal")

            # NEW: Bollinger Band squeeze breakout
            # Tight BB width then directional close outside the band = expansion.
            bb_width_pct = float(ind.get("bb_width_pct") or 0)
            bb_u = float(ind.get("bb_upper") or c)
            bb_l = float(ind.get("bb_lower") or c)
            if bb_width_pct > 0 and bb_width_pct < 4.0:  # squeezed (<4% of price)
                if c > bb_u and ind.get("rel_volume", 1) > 1.1:
                    signals.append("BUY_CALL"); reasons.append(f"BB squeeze breakout↑ (w={bb_width_pct:.1f}%)")
                elif c < bb_l and ind.get("rel_volume", 1) > 1.1:
                    signals.append("BUY_PUT"); reasons.append(f"BB squeeze breakout↓ (w={bb_width_pct:.1f}%)")

            # Price structure
            if n >= 5:
                if highs[-1] > highs[-5] and lows[-1] > lows[-5]:
                    signals.append("BUY_CALL"); reasons.append("Higher highs + lows (uptrend)")
                elif highs[-1] < highs[-5] and lows[-1] < lows[-5]:
                    signals.append("BUY_PUT"); reasons.append("Lower highs + lows (downtrend)")
            # SuperTrend
            if ind.get("supertrend_dir") == "up":
                signals.append("BUY_CALL"); reasons.append(f"SuperTrend bullish")
            else:
                signals.append("BUY_PUT"); reasons.append("SuperTrend bearish")
            # Pivot breakout
            pivot_bias = ind.get("pivot_bias", "neutral")
            if pivot_bias == "bullish_breakout":
                signals.append("BUY_CALL"); reasons.append("Pivot R1 breakout")
            elif pivot_bias == "bearish_breakdown":
                signals.append("BUY_PUT"); reasons.append("Pivot S1 breakdown")
            # Ichimoku confirmation
            ichi = ind.get("ichimoku_signal", "neutral")
            if ichi == "bullish": signals.append("BUY_CALL"); reasons.append("Above Ichimoku cloud")
            elif ichi == "bearish": signals.append("BUY_PUT"); reasons.append("Below Ichimoku cloud")

            # NEW: Relative strength vs SPY
            # If this stock outperformed SPY by >0.6% today → bullish RS,
            # underperformed by >0.6% → bearish RS. Strong directional edge
            # because it tells us the stock has its own momentum.
            spy = ind.get("spy_trend") or {}
            spy_chg = float(spy.get("change_1d") or 0)
            stock_chg = float(ind.get("change_1d") or 0)
            rs_diff = stock_chg - spy_chg
            if abs(rs_diff) >= 0.6 and spy.get("dir") != "self":
                if rs_diff > 0:
                    signals.append("BUY_CALL"); reasons.append(f"RS vs SPY +{rs_diff:.1f}%")
                else:
                    signals.append("BUY_PUT"); reasons.append(f"RS vs SPY {rs_diff:.1f}%")

            calls = signals.count("BUY_CALL")
            puts = signals.count("BUY_PUT")
            total = max(calls + puts, 1)
            conf = 55 + (max(calls, puts) / total) * 30
            r = " | ".join(reasons[:3])
            if calls > puts:
                return _vote(self.name, self.emoji, "BUY_CALL", conf, r)
            elif puts > calls:
                return _vote(self.name, self.emoji, "BUY_PUT", conf, r)
            return _hold(self.name, self.emoji, r or "No clear pattern")
        except Exception as e:
            return _hold(self.name, self.emoji, f"Error: {e}")


# ─────────────────────────────────────────────────────────────────────────────
# 2. TECHNICAL AGENT
# ─────────────────────────────────────────────────────────────────────────────
class TechnicalAgent:
    name = "Technical Agent"
    emoji = "📈"
    method = "RSI + MACD + Bollinger + SuperTrend + Stochastic + ADX + Williams %R + Ichimoku"

    def analyze(self, df, ind):
        try:
            result = score_indicators_to_direction(ind)
            direction = result["direction"]
            conf = result["confidence"]
            score = result["score"]

            adx = ind.get("adx", 20)
            rsi = ind.get("rsi14", 50)
            wr = ind.get("williams_r", -50)
            ichi = ind.get("ichimoku_signal", "neutral")
            div = ind.get("rsi_divergence", "none")

            reasons = [
                f"Score {score:+.1f}/12 | ADX {adx:.0f}({'TREND' if adx>25 else 'CHOP'})",
                f"RSI {rsi:.0f} | W%R {wr:.0f} | Ichimoku {ichi}",
                f"Divergence: {div}" if div != "none" else f"MACD hist {ind.get('macd_hist',0):+.4f}",
            ]

            # ADX filter: if market is choppy (ADX < 15), downgrade confidence
            if adx < 15 and direction != "NEUTRAL":
                conf *= 0.75
                reasons[0] += " [LOW ADX — caution]"

            if direction == "BULLISH":
                return _vote(self.name, self.emoji, "BUY_CALL", conf, " | ".join(reasons))
            elif direction == "BEARISH":
                return _vote(self.name, self.emoji, "BUY_PUT", conf, " | ".join(reasons))
            return _hold(self.name, self.emoji, f"Neutral score {score:+.1f}" + " | " + reasons[1])
        except Exception as e:
            return _hold(self.name, self.emoji, f"Error: {e}")


# ─────────────────────────────────────────────────────────────────────────────
# 3. VOLUME AGENT
# ─────────────────────────────────────────────────────────────────────────────
class VolumeAgent:
    name = "Volume Agent"
    emoji = "📦"
    method = "Relative volume + OBV slope + Up/Down vol ratio + Volume trend + VWAP confirmation"

    def analyze(self, df, ind):
        try:
            rel_v = ind.get("rel_volume", 1.0)
            obv_slope = ind.get("obv_slope_10d_pct", 0.0)
            up_dn = ind.get("up_dn_vol_ratio", 1.0)
            vol_trend = ind.get("vol_trend_5v20", 1.0)
            vc = ind.get("vol_confirms", "neutral")
            ch = ind.get("change_1d", 0)
            pvwap = ind.get("price_vs_vwap_pct", 0)

            signals, reasons = [], []

            if rel_v > 2.0:
                reasons.append(f"Volume surge {rel_v:.1f}×")
                signals.append("BUY_CALL" if ch > 0 else "BUY_PUT")
            elif rel_v > 1.5:
                reasons.append(f"Above-avg vol {rel_v:.1f}×")
                signals.append("BUY_CALL" if ch > 0 else "BUY_PUT")
            if obv_slope > 8:
                signals.append("BUY_CALL"); reasons.append(f"OBV +{obv_slope:.0f}% (accumulation)")
            elif obv_slope < -8:
                signals.append("BUY_PUT"); reasons.append(f"OBV {obv_slope:.0f}% (distribution)")
            if up_dn > 1.4:
                signals.append("BUY_CALL"); reasons.append(f"Accumulation ratio {up_dn:.2f}×")
            elif up_dn < 0.7:
                signals.append("BUY_PUT"); reasons.append(f"Distribution ratio {up_dn:.2f}×")
            if vol_trend > 1.3:
                reasons.append(f"Volume building {vol_trend:.1f}×")
                signals.append("BUY_CALL" if ch > 0 else "BUY_PUT")
            if vc == "confirms" and ch > 0:
                signals.append("BUY_CALL"); reasons.append("Vol confirms bullish")
            elif vc == "confirms" and ch < 0:
                signals.append("BUY_PUT"); reasons.append("Vol confirms bearish")
            # VWAP
            if pvwap > 1.5:
                signals.append("BUY_CALL"); reasons.append(f"Price {pvwap:.1f}% above VWAP")
            elif pvwap < -1.5:
                signals.append("BUY_PUT"); reasons.append(f"Price {pvwap:.1f}% below VWAP")

            calls = signals.count("BUY_CALL")
            puts = signals.count("BUY_PUT")
            conf = 55 + min(rel_v * 6, 25)
            r = " | ".join(reasons[:3]) or f"Vol {rel_v:.1f}× neutral"
            if calls > puts:
                return _vote(self.name, self.emoji, "BUY_CALL", conf, r)
            elif puts > calls:
                return _vote(self.name, self.emoji, "BUY_PUT", conf, r)
            return _hold(self.name, self.emoji, r)
        except Exception as e:
            return _hold(self.name, self.emoji, f"Error: {e}")


# ─────────────────────────────────────────────────────────────────────────────
# 4. SENTIMENT AGENT
# ─────────────────────────────────────────────────────────────────────────────
class SentimentAgent:
    name = "Sentiment Agent"
    emoji = "📰"
    method = "Yahoo Finance news headline NLP scoring + 5-day price trend proxy"

    BULLISH = ["surge","rally","gain","rise","jump","soar","beat","exceed","record","high","growth",
               "profit","upgrade","bullish","positive","strong","boost","breakout","outperform",
               "partnership","acquisition","innovation","revenue","approval","launch","deal",
               "raises","guidance","recovery","expansion","beats","raises","dividend"]
    BEARISH = ["drop","fall","crash","decline","plunge","miss","loss","sell","downgrade","bearish",
               "negative","weak","cut","layoff","risk","concern","warn","volatile","uncertainty",
               "lawsuit","fraud","recall","shortage","debt","deficit","investigation","probe",
               "default","bankruptcy","missed","disappoints","suspended","warning","slump"]

    def analyze(self, df, ind):
        try:
            news = ind.get("_news", [])
            if not news:
                ch5 = ind.get("change_5d", 0)
                if ch5 > 3: return _vote(self.name, self.emoji, "BUY_CALL", 62, f"5D trend +{ch5:.1f}% (no live news)")
                elif ch5 < -3: return _vote(self.name, self.emoji, "BUY_PUT", 62, f"5D trend {ch5:.1f}% (no live news)")
                return _hold(self.name, self.emoji, "No news; price trend neutral")

            bull_score = bear_score = 0
            for item in news[:12]:
                title = (item.get("title", "") + " " + item.get("summary", "")).lower()
                for w in self.BULLISH:
                    if w in title: bull_score += 1
                for w in self.BEARISH:
                    if w in title: bear_score += 1

            total = bull_score + bear_score
            if total == 0:
                return _hold(self.name, self.emoji, "Neutral news sentiment")

            ratio = bull_score / total
            conf = 55 + abs(bull_score - bear_score) / max(total, 1) * 30
            if ratio > 0.6:
                return _vote(self.name, self.emoji, "BUY_CALL", conf, f"News bullish {bull_score}↑/{bear_score}↓")
            elif ratio < 0.4:
                return _vote(self.name, self.emoji, "BUY_PUT", conf, f"News bearish {bear_score}↓/{bull_score}↑")
            return _hold(self.name, self.emoji, f"Mixed news {bull_score}↑/{bear_score}↓")
        except Exception as e:
            return _hold(self.name, self.emoji, f"Error: {e}")


# ─────────────────────────────────────────────────────────────────────────────
# 5. OPTIONS FLOW AGENT
# ─────────────────────────────────────────────────────────────────────────────
class OptionsFlowAgent:
    name = "Options Flow Agent"
    emoji = "🎯"
    method = "Put/Call OI ratio + Put/Call volume ratio (real options chain from Yahoo Finance)"

    def analyze(self, df, ind):
        try:
            import yfinance as yf
            symbol = ind.get("_symbol", "")
            if not symbol:
                return _hold(self.name, self.emoji, "No symbol")
            ticker = yf.Ticker(symbol)
            dates = ticker.options
            if not dates:
                return _hold(self.name, self.emoji, "No options chain")

            chain0 = ticker.option_chain(dates[0])
            calls = chain0.calls
            puts = chain0.puts
            total_call_oi = safe_float(calls["openInterest"].sum()) if "openInterest" in calls.columns else 0
            total_put_oi = safe_float(puts["openInterest"].sum()) if "openInterest" in puts.columns else 0
            total_call_vol = safe_float(calls["volume"].sum()) if "volume" in calls.columns else 0
            total_put_vol = safe_float(puts["volume"].sum()) if "volume" in puts.columns else 0

            pc_oi = total_put_oi / total_call_oi if total_call_oi > 0 else 1
            pc_vol = total_put_vol / total_call_vol if total_call_vol > 0 else 1
            total_vol = total_call_vol + total_put_vol
            reasons = [f"P/C OI:{pc_oi:.2f}", f"P/C Vol:{pc_vol:.2f}"]

            # ── Evidence-quality gate #1: minimum option volume ─────────
            # Thinly-traded chains produce noisy ratios — a single big trade
            # can flip the P/C ratio. Require at least 1,000 contracts of
            # combined volume before trusting the signal at all.
            if total_vol < 1000:
                return _hold(
                    self.name, self.emoji,
                    f"Thin options volume ({int(total_vol)} contracts) — ratio unreliable",
                )

            # ── Evidence-quality gate #2: tape confirmation ─────────────
            # Options flow alone is contrarian-prone: heavy put buying
            # often happens AS hedging into rallies, not because the stock
            # is about to fall. Confirm with the actual price tape:
            #   bullish tape  = supertrend up  AND ema9 > ema21
            #   bearish tape  = supertrend dn  AND ema9 < ema21
            #   mixed tape    = anything else
            st_dir = ind.get("supertrend_dir", "up")
            ema9 = ind.get("ema9", 0)
            ema21 = ind.get("ema21", 0)
            tape_bull = (st_dir == "up") and (ema9 > ema21)
            tape_bear = (st_dir == "down") and (ema9 < ema21)

            # Decide raw direction from option flow
            if pc_vol < 0.5:    raw_dir, raw_conf, label = "BUY_CALL", 82, "Heavy call flow"
            elif pc_vol < 0.7:  raw_dir, raw_conf, label = "BUY_CALL", 70, "Call dominance"
            elif pc_vol > 2.0:  raw_dir, raw_conf, label = "BUY_PUT",  82, "Heavy put flow"
            elif pc_vol > 1.4:  raw_dir, raw_conf, label = "BUY_PUT",  70, "Put dominance"
            elif pc_oi  < 0.7:  raw_dir, raw_conf, label = "BUY_CALL", 63, "Call OI dominance"
            elif pc_oi  > 1.3:  raw_dir, raw_conf, label = "BUY_PUT",  63, "Put OI dominance"
            else:
                return _hold(self.name, self.emoji, f"Neutral flow — {' '.join(reasons)}")

            # Tape contradicts flow → HOLD ("nothing backing it up")
            if raw_dir == "BUY_CALL" and tape_bear:
                return _hold(
                    self.name, self.emoji,
                    f"{label} but tape bearish (ST down, EMA9<EMA21) — no confirmation",
                )
            if raw_dir == "BUY_PUT" and tape_bull:
                return _hold(
                    self.name, self.emoji,
                    f"{label} but tape bullish (ST up, EMA9>EMA21) — no confirmation",
                )

            # Tape mixed → trim confidence; tape aligned → keep it
            tape_aligned = (raw_dir == "BUY_CALL" and tape_bull) or (raw_dir == "BUY_PUT" and tape_bear)
            if not tape_aligned:
                raw_conf = max(55.0, raw_conf * 0.75)
                label += " (mixed tape)"

            return _vote(self.name, self.emoji, raw_dir, raw_conf, f"{label} — {' '.join(reasons)}")
        except Exception as e:
            return _hold(self.name, self.emoji, f"Options unavailable: {e}")


# ─────────────────────────────────────────────────────────────────────────────
# 6. MOMENTUM AGENT
# ─────────────────────────────────────────────────────────────────────────────
class MomentumAgent:
    name = "Momentum Agent"
    emoji = "⚡"
    method = "ROC-5/10 + 20D breakout + consecutive streak + VWAP deviation + ADX +DI/-DI"

    def analyze(self, df, ind):
        try:
            closes = df["Close"].values
            highs = df["High"].values
            lows = df["Low"].values
            n = len(closes)
            if n < 10:
                return _hold(self.name, self.emoji, "Not enough data")

            price = closes[-1]
            signals, reasons = [], []

            roc5 = (closes[-1] - closes[-5]) / closes[-5] * 100 if n >= 5 and closes[-5] > 0 else 0
            roc10 = (closes[-1] - closes[-10]) / closes[-10] * 100 if n >= 10 and closes[-10] > 0 else 0

            if roc5 > 2: signals.append("BUY_CALL"); reasons.append(f"ROC5 +{roc5:.1f}%")
            elif roc5 < -2: signals.append("BUY_PUT"); reasons.append(f"ROC5 {roc5:.1f}%")
            if roc10 > 4: signals.append("BUY_CALL"); reasons.append(f"ROC10 +{roc10:.1f}%")
            elif roc10 < -4: signals.append("BUY_PUT"); reasons.append(f"ROC10 {roc10:.1f}%")

            h20 = np.max(highs[-20:]) if n >= 20 else np.max(highs)
            l20 = np.min(lows[-20:]) if n >= 20 else np.min(lows)
            if price >= h20 * 0.99: signals.append("BUY_CALL"); reasons.append(f"20D breakout high ${h20:.2f}")
            elif price <= l20 * 1.01: signals.append("BUY_PUT"); reasons.append(f"20D breakdown low ${l20:.2f}")

            # Streak
            bull_streak = bear_streak = 0
            for i in range(n-1, max(n-7, 0), -1):
                if closes[i] > closes[i-1]: bull_streak += 1
                else: break
            for i in range(n-1, max(n-7, 0), -1):
                if closes[i] < closes[i-1]: bear_streak += 1
                else: break
            if bull_streak >= 3: signals.append("BUY_CALL"); reasons.append(f"{bull_streak}-day streak up")
            if bear_streak >= 3: signals.append("BUY_PUT"); reasons.append(f"{bear_streak}-day streak down")

            # VWAP
            pvwap = ind.get("price_vs_vwap_pct", 0)
            if pvwap > 1.0: signals.append("BUY_CALL"); reasons.append(f"VWAP +{pvwap:.1f}%")
            elif pvwap < -1.0: signals.append("BUY_PUT"); reasons.append(f"VWAP {pvwap:.1f}%")

            # ADX directional
            plus_di = ind.get("plus_di", 25)
            minus_di = ind.get("minus_di", 25)
            if plus_di > minus_di + 8: signals.append("BUY_CALL"); reasons.append(f"+DI({plus_di:.0f})>-DI({minus_di:.0f})")
            elif minus_di > plus_di + 8: signals.append("BUY_PUT"); reasons.append(f"-DI({minus_di:.0f})>+DI({plus_di:.0f})")

            calls = signals.count("BUY_CALL")
            puts = signals.count("BUY_PUT")
            total = max(calls + puts, 1)
            conf = 55 + (max(calls, puts) / total) * 32
            r = " | ".join(reasons[:3]) or f"ROC5:{roc5:+.1f}%"
            if calls > puts: return _vote(self.name, self.emoji, "BUY_CALL", conf, r)
            elif puts > calls: return _vote(self.name, self.emoji, "BUY_PUT", conf, r)
            return _hold(self.name, self.emoji, r)
        except Exception as e:
            return _hold(self.name, self.emoji, f"Error: {e}")


# ─────────────────────────────────────────────────────────────────────────────
# 7. RISK AGENT
# ─────────────────────────────────────────────────────────────────────────────
class RiskAgent:
    name = "Risk Agent"
    emoji = "🛡️"
    method = "ATR stop/target + volatility regime + 52W position + Fibonacci proximity + ADX filter"

    def analyze(self, df, ind):
        try:
            price = ind.get("price", df["Close"].iloc[-1])
            atr = ind.get("atr14", price * 0.02)
            vola = ind.get("volatility_20d", 25)
            adx = ind.get("adx", 20)

            signals, reasons = [], []

            if vola < 20:
                signals.append("BUY_CALL"); reasons.append(f"Low vol {vola:.0f}% — options cheap")
            elif vola > 50:
                signals.append("BUY_PUT"); reasons.append(f"Extreme vol {vola:.0f}% — premium elevated")
            else:
                reasons.append(f"Moderate vol {vola:.0f}%")

            atr_pct = atr / price * 100 if price > 0 else 2
            if atr_pct < 1.5: signals.append("BUY_CALL"); reasons.append(f"Tight ATR {atr_pct:.1f}%")
            elif atr_pct > 4: signals.append("BUY_PUT"); reasons.append(f"Wide ATR {atr_pct:.1f}%")

            h52 = ind.get("high_52w", 0); l52 = ind.get("low_52w", 0)
            if h52 > 0 and l52 > 0:
                pos52 = (price - l52) / (h52 - l52) * 100
                if pos52 > 85: reasons.append(f"Near 52W high ({pos52:.0f}%) — extended")
                elif pos52 < 15: reasons.append(f"Near 52W low ({pos52:.0f}%) — potential base")

            # Fibonacci proximity (golden ratio is high probability)
            fib618 = ind.get("fibonacci", {}).get("fib_618", 0)
            if fib618 and abs(price - fib618) / price < 0.015:
                signals.append("BUY_CALL"); reasons.append(f"At 61.8% Fib ${fib618:.2f} (golden ratio support)")

            # ADX: only trade strong trends
            if adx > 30: reasons.append(f"ADX {adx:.0f} — strong trend, good risk")
            elif adx < 18: reasons.append(f"ADX {adx:.0f} — choppy, reduce size")

            stop_long = round(price - 2 * atr, 2)
            stop_short = round(price + 2 * atr, 2)
            tgt_long = round(price + 3 * atr, 2)
            tgt_short = round(price - 3 * atr, 2)

            calls = signals.count("BUY_CALL")
            puts = signals.count("BUY_PUT")
            conf = 60 + abs(calls - puts) * 8
            base = {"stop_loss_long": stop_long, "stop_loss_short": stop_short,
                    "target_long": tgt_long, "target_short": tgt_short,
                    "atr": round(atr, 3), "volatility_pct": round(vola, 1)}
            r = " | ".join(reasons[:3])
            if calls > puts: return {**_vote(self.name, self.emoji, "BUY_CALL", conf, r), **base}
            elif puts > calls: return {**_vote(self.name, self.emoji, "BUY_PUT", conf, r), **base}
            return {**_hold(self.name, self.emoji, r), **base}
        except Exception as e:
            return {**_hold(self.name, self.emoji, f"Error: {e}"),
                    "stop_loss_long": 0, "stop_loss_short": 0,
                    "target_long": 0, "target_short": 0, "atr": 0, "volatility_pct": 25}


# ─────────────────────────────────────────────────────────────────────────────
# 8. FEAR & GREED AGENT  ← NEW
# ─────────────────────────────────────────────────────────────────────────────
class FearGreedAgent:
    name = "Fear & Greed Agent"
    emoji = "😱"
    method = "VIX level + SPY Put/Call ratio + SPY 125-day momentum = Fear/Greed score (0-100)"

    _cache: dict = {}
    _cache_ts: float = 0
    CACHE_TTL = 60  # 1 minute — keeps the gauge moving instead of frozen

    def _compute_fear_greed(self) -> dict:
        """Compute CNN-style Fear & Greed Index from real market data."""
        if time.time() - self._cache_ts < self.CACHE_TTL and self._cache:
            return self._cache

        import yfinance as yf
        components = []
        score = 50.0  # default neutral

        # 1. VIX (40% weight — most important)
        try:
            vix_info = yf.Ticker("^VIX").fast_info
            vix = safe_float(getattr(vix_info, "last_price", None))
            if vix > 0:
                if vix < 12: vs = 92
                elif vix < 15: vs = 78
                elif vix < 20: vs = 63
                elif vix < 25: vs = 45
                elif vix < 30: vs = 30
                elif vix < 40: vs = 18
                else: vs = 8
                components.append({"name": "VIX", "score": vs, "value": round(vix, 2),
                                   "weight": 0.40, "label": f"VIX {vix:.1f}"})
        except Exception as e:
            logger.debug(f"VIX fetch: {e}")

        # 2. SPY momentum vs 125-day SMA (30% weight)
        try:
            spy_df = yf.Ticker("SPY").history(period="7mo", interval="1d")
            if len(spy_df) >= 125:
                sma125 = spy_df["Close"].rolling(125).mean().iloc[-1]
                curr = spy_df["Close"].iloc[-1]
                pct = (curr - sma125) / sma125 * 100
                if pct > 8: ms = 90
                elif pct > 4: ms = 75
                elif pct > 1: ms = 62
                elif pct > 0: ms = 53
                elif pct > -4: ms = 40
                elif pct > -8: ms = 25
                else: ms = 12
                components.append({"name": "SPY Momentum", "score": ms, "value": round(pct, 2),
                                   "weight": 0.30, "label": f"SPY vs 125SMA {pct:+.1f}%"})
        except Exception as e:
            logger.debug(f"SPY momentum: {e}")

        # 3. SPY Put/Call volume ratio (20% weight)
        try:
            spy_opts = yf.Ticker("SPY")
            dates = spy_opts.options
            if dates:
                chain = spy_opts.option_chain(dates[0])
                call_vol = safe_float(chain.calls["volume"].sum())
                put_vol = safe_float(chain.puts["volume"].sum())
                pc_vol = put_vol / call_vol if call_vol > 0 else 1
                if pc_vol < 0.5: ps = 90
                elif pc_vol < 0.7: ps = 75
                elif pc_vol < 0.9: ps = 60
                elif pc_vol < 1.1: ps = 45
                elif pc_vol < 1.5: ps = 30
                else: ps = 15
                components.append({"name": "Put/Call", "score": ps, "value": round(pc_vol, 3),
                                   "weight": 0.20, "label": f"P/C ratio {pc_vol:.2f}"})
        except Exception as e:
            logger.debug(f"P/C ratio: {e}")

        # 4. Junk bond proxy — HYG vs IEF performance (10% weight)
        try:
            hyg_df = yf.Ticker("HYG").history(period="5d", interval="1d")
            ief_df = yf.Ticker("IEF").history(period="5d", interval="1d")
            if len(hyg_df) >= 2 and len(ief_df) >= 2:
                hyg_ret = (hyg_df["Close"].iloc[-1] - hyg_df["Close"].iloc[-2]) / hyg_df["Close"].iloc[-2] * 100
                ief_ret = (ief_df["Close"].iloc[-1] - ief_df["Close"].iloc[-2]) / ief_df["Close"].iloc[-2] * 100
                spread = hyg_ret - ief_ret  # positive = risk-on (greed)
                if spread > 0.3: js = 80
                elif spread > 0: js = 62
                elif spread > -0.3: js = 45
                else: js = 25
                components.append({"name": "Junk Bond Demand", "score": js, "value": round(spread, 3),
                                   "weight": 0.10, "label": f"HYG-IEF spread {spread:+.3f}%"})
        except Exception as e:
            logger.debug(f"Junk bond: {e}")

        if components:
            total_weight = sum(c["weight"] for c in components)
            score = sum(c["score"] * c["weight"] for c in components) / total_weight

        score = round(score, 1)
        if score >= 75: label, color = "Extreme Greed", "#10b981"
        elif score >= 55: label, color = "Greed", "#22c55e"
        elif score >= 45: label, color = "Neutral", "#f59e0b"
        elif score >= 25: label, color = "Fear", "#f97316"
        else: label, color = "Extreme Fear", "#ef4444"

        result = {"score": score, "label": label, "color": color, "components": components}
        FearGreedAgent._cache = result
        FearGreedAgent._cache_ts = time.time()
        return result

    def analyze(self, df, ind):
        try:
            fg = self._compute_fear_greed()
            score = fg["score"]
            label = fg["label"]

            reasons = [f"Fear & Greed: {score}/100 — {label}"]
            for c in fg["components"][:2]:
                reasons.append(c["label"])

            # Trading signal based on score
            if score >= 75:
                # Extreme Greed = market overbought → contrarian PUT
                return _vote(self.name, self.emoji, "BUY_PUT", 74,
                             f"Extreme Greed ({score}) — contrarian bearish | " + " | ".join(reasons))
            elif score >= 60:
                # Greed = mild bullish (trend following)
                return _vote(self.name, self.emoji, "BUY_CALL", 65,
                             f"Greed ({score}) — trend continues bullish | " + " | ".join(reasons))
            elif score <= 25:
                # Extreme Fear = market oversold → contrarian CALL
                return _vote(self.name, self.emoji, "BUY_CALL", 78,
                             f"Extreme Fear ({score}) — contrarian bullish buy the dip | " + " | ".join(reasons))
            elif score <= 40:
                # Fear = mild bearish
                return _vote(self.name, self.emoji, "BUY_PUT", 62,
                             f"Fear ({score}) — market weak | " + " | ".join(reasons))
            return _hold(self.name, self.emoji, f"Neutral sentiment ({score}/100) — no edge")
        except Exception as e:
            return _hold(self.name, self.emoji, f"Fear/Greed unavailable: {e}")


# ─────────────────────────────────────────────────────────────────────────────
# 9. POLITICAL / TRUMP AGENT  ← NEW
# ─────────────────────────────────────────────────────────────────────────────
class PoliticalAgent:
    name = "Political Agent"
    emoji = "🏛️"
    method = "Google News RSS scraper for Trump + tariff + Fed + macro keywords — market impact scoring"

    MARKET_BULLISH = [
        "tax cut", "deregulation", "stimulus", "deal", "agreement", "rate cut",
        "rate hold", "pause", "eases", "boosts", "supports", "pro-business",
        "infrastructure", "signed", "passed", "boom", "recovery", "strong economy",
        "jobs added", "beats expectations", "trade deal", "ceasefire", "peace",
        "tariff removed", "exemption", "positive", "rally", "gains"
    ]
    MARKET_BEARISH = [
        "tariff", "trade war", "sanction", "ban", "escalate", "retaliate",
        "recession", "inflation", "hike", "rate hike", "hawkish", "tightening",
        "debt ceiling", "shutdown", "default", "war", "conflict", "tension",
        "investigation", "indicted", "impeach", "crisis", "crash", "plunge",
        "layoff", "bankruptcy", "losses", "miss", "disappoints", "uncertainty",
        "tariffs raised", "china", "new tariff", "additional tariff"
    ]

    _news_cache: list = []
    _cache_ts: float = 0
    CACHE_TTL = 120  # 2 minutes

    def _fetch_political_news(self) -> list:
        if time.time() - PoliticalAgent._cache_ts < self.CACHE_TTL and PoliticalAgent._news_cache:
            return PoliticalAgent._news_cache

        queries = [
            "trump tariff stock market economy",
            "federal reserve interest rate economy",
            "US economy recession inflation",
        ]
        all_news = []
        for q in queries[:2]:
            try:
                q_enc = q.replace(" ", "+")
                url = f"https://news.google.com/rss/search?q={q_enc}&hl=en-US&gl=US&ceid=US:en"
                req = urllib.request.Request(url, headers={
                    "User-Agent": "Mozilla/5.0 (compatible; TradeSignalAI/1.0)"
                })
                with urllib.request.urlopen(req, timeout=6) as resp:
                    content = resp.read()
                root = ET.fromstring(content)
                for item in root.findall(".//item")[:6]:
                    title = html_lib.unescape(item.findtext("title", ""))
                    link = item.findtext("link", "")
                    pub = item.findtext("pubDate", "")
                    source_el = item.find("{http://purl.org/dc/elements/1.1/}creator")
                    source = source_el.text if source_el is not None else "Google News"
                    all_news.append({
                        "title": title,
                        "url": link,
                        "source": source,
                        "published_at": pub,
                        "category": "political",
                    })
            except Exception as e:
                logger.debug(f"Google News fetch failed: {e}")

        PoliticalAgent._news_cache = all_news
        PoliticalAgent._cache_ts = time.time()
        return all_news

    def analyze(self, df, ind):
        try:
            news = self._fetch_political_news()
            # Also check Yahoo Finance news for political keywords
            yahoo_news = ind.get("_news", [])
            all_news = news + yahoo_news

            if not all_news:
                return _hold(self.name, self.emoji, "No political news available")

            bull = bear = 0
            top_headlines = []
            for item in all_news[:15]:
                title = (item.get("title", "") + " " + item.get("summary", "")).lower()
                item_bull = sum(1 for w in self.MARKET_BULLISH if w in title)
                item_bear = sum(1 for w in self.MARKET_BEARISH if w in title)
                bull += item_bull
                bear += item_bear
                if item_bull > 0 or item_bear > 0:
                    top_headlines.append(item.get("title", "")[:60])

            total = bull + bear
            if total == 0:
                return _hold(self.name, self.emoji, "Politically neutral news cycle")

            ratio = bull / total
            conf = 54 + abs(bull - bear) / max(total, 1) * 28
            headline_str = top_headlines[0][:50] if top_headlines else ""

            if ratio > 0.62:
                return _vote(self.name, self.emoji, "BUY_CALL", conf,
                             f"Pro-market news {bull}↑/{bear}↓ | {headline_str}")
            elif ratio < 0.38:
                return _vote(self.name, self.emoji, "BUY_PUT", conf,
                             f"Anti-market news {bear}↓/{bull}↑ | {headline_str}")
            return _hold(self.name, self.emoji, f"Mixed macro/political signals {bull}↑/{bear}↓")
        except Exception as e:
            return _hold(self.name, self.emoji, f"Political data unavailable: {e}")


# ─────────────────────────────────────────────────────────────────────────────
# TARGET-HIT PROBABILITY  (replaces the old "agent vote average" confidence)
# ─────────────────────────────────────────────────────────────────────────────
def compute_target_hit_probability(
    *,
    signal: str,
    price: float,
    target: float,
    atr: float,
    ind: dict,
    days: int = 7,
    hist_hit_rate: float | None = None,
) -> dict:
    """
    Estimate the probability that price will TOUCH `target` within `days`
    trading days, combining:

      A. Volatility-grounded base rate (Brownian first-passage formula
         using ATR as the daily vol proxy).  Far targets vs daily noise
         → low base; close targets → high base.

      B. Directional alignment of the full indicator suite —
         SuperTrend, EMA 9/21, MACD, RSI, Bollinger position,
         Volume (rel + up/dn ratio), OBV slope, ADX trend, Williams %R,
         Ichimoku, VWAP, Pivot bias, Stochastic, multi-TF trend.
         Each indicator votes for or against the target direction;
         the weighted consensus boosts (or suppresses) the base rate.

      C. Per-stock historical hit-rate calibration — blends in the
         model's actual track record on this specific symbol.

    Returns: { prob_pct, base_pct, alignment, alignment_pct_boost,
               breakdown[], method, days }
    """
    # HOLD or degenerate inputs → meaningless
    if signal == "HOLD" or price <= 0 or target == price or atr <= 0:
        return {
            "prob_pct": 50.0,
            "base_pct": 50.0,
            "alignment": 0.0,
            "alignment_pct_boost": 0.0,
            "breakdown": [],
            "method": "neutral (no directional signal)",
            "days": days,
        }

    # ── A. Volatility-based first-passage probability ───────────────
    # 1 ATR ≈ 1 day's expected price range, so σ_daily ≈ atr / price.
    # Probability of touching a barrier D away within N days under
    # zero-drift Brownian motion: 2·(1 − Φ(D / (σ·√N))).
    sigma_daily = atr / price
    distance_pct = abs(target - price) / price
    z = distance_pct / (sigma_daily * math.sqrt(max(days, 1)))
    p_base = 2.0 * (1.0 - norm.cdf(z))
    p_base = max(0.05, min(0.95, p_base))

    # ── B. Directional alignment score in [-1, +1] ──────────────────
    is_call = (signal == "BUY_CALL")
    breakdown: list[dict] = []
    total_signed = 0.0
    total_weight = 0.0

    def _add(name: str, weight: float, bull_cond: bool, bear_cond: bool, detail: str = ""):
        nonlocal total_signed, total_weight
        if bull_cond:
            contrib = weight if is_call else -weight
            arrow = "↑"
        elif bear_cond:
            contrib = -weight if is_call else weight
            arrow = "↓"
        else:
            contrib = 0.0
            arrow = "·"
        total_signed += contrib
        total_weight += weight
        breakdown.append({
            "indicator": name,
            "direction": arrow,
            "weight": weight,
            "contrib": round(contrib, 2),
            "detail": detail,
            "supports_target": contrib > 0,
        })

    # SuperTrend (highest weight — primary trend follower)
    st_dir = ind.get("supertrend_dir", "")
    _add("SuperTrend", 2.0, st_dir == "up", st_dir == "down", f"{st_dir or 'n/a'}")

    # Multi-timeframe composite trend
    trend = float(ind.get("trend_score") or 0)
    _add("Multi-TF Trend", 1.5, trend > 0.3, trend < -0.3, f"score {trend:+.2f}")

    # Volume confirmation (relative volume + up/down vol balance)
    rel_vol = float(ind.get("rel_volume") or 1.0)
    ud_ratio = float(ind.get("up_dn_vol_ratio") or 1.0)
    _add("Volume", 1.2,
         rel_vol > 1.3 and ud_ratio > 1.1,
         rel_vol > 1.3 and ud_ratio < 0.9,
         f"{rel_vol:.2f}x avg, U/D {ud_ratio:.2f}")

    # EMA 9/21 crossover
    ema9 = float(ind.get("ema9") or 0)
    ema21 = float(ind.get("ema21") or 0)
    _add("EMA 9/21", 1.0, ema9 > ema21, ema9 < ema21,
         f"{ema9:.2f} vs {ema21:.2f}")

    # MACD direction
    macd = float(ind.get("macd") or 0)
    macd_sig = float(ind.get("macd_signal") or 0)
    _add("MACD", 1.0, macd > macd_sig, macd < macd_sig,
         f"{macd:+.3f} vs {macd_sig:+.3f}")

    # RSI momentum (50–70 bullish, 30–50 bearish; outside = exhaustion → neutral)
    rsi = float(ind.get("rsi14") or 50)
    _add("RSI", 1.0, 50 < rsi < 70, 30 < rsi < 50, f"{rsi:.1f}")

    # OBV slope (institutional accumulation)
    obv_slope = float(ind.get("obv_slope_10d_pct") or 0)
    _add("OBV Trend", 1.0, obv_slope > 1.0, obv_slope < -1.0,
         f"{obv_slope:+.1f}% / 10d")

    # ADX trend strength (only counts when DI direction is established)
    adx = float(ind.get("adx") or 0)
    plus_di = float(ind.get("plus_di") or 0)
    minus_di = float(ind.get("minus_di") or 0)
    _add("ADX Trend", 1.0,
         adx >= 25 and plus_di > minus_di,
         adx >= 25 and minus_di > plus_di,
         f"ADX {adx:.0f}, +DI {plus_di:.0f} / -DI {minus_di:.0f}")

    # Ichimoku cloud signal
    ichi = str(ind.get("ichimoku_signal") or "neutral").lower()
    _add("Ichimoku", 1.0, "bull" in ichi, "bear" in ichi, ichi)

    # Bollinger Band position (z within band)
    bb_u = float(ind.get("bb_upper") or price * 1.05)
    bb_l = float(ind.get("bb_lower") or price * 0.95)
    bb_m = float(ind.get("bb_mid") or price)
    bb_w = bb_u - bb_l
    bb_z = ((price - bb_m) / (bb_w / 2)) if bb_w > 0 else 0.0
    _add("Bollinger Pos", 0.8, 0 < bb_z < 0.7, -0.7 < bb_z < 0,
         f"z {bb_z:+.2f}")

    # VWAP relationship
    vwap_pct = float(ind.get("price_vs_vwap_pct") or 0)
    _add("VWAP", 0.8, vwap_pct > 0.2, vwap_pct < -0.2, f"{vwap_pct:+.2f}%")

    # Pivot bias
    pb = str(ind.get("pivot_bias") or "neutral")
    _add("Pivots", 0.8, "bull" in pb, "bear" in pb, pb)

    # Stochastic
    stoch = float(ind.get("stoch_k") or 50)
    _add("Stochastic", 0.5, 50 < stoch < 80, 20 < stoch < 50, f"K {stoch:.0f}")

    # Williams %R (-50..-20 = bullish zone, -80..-50 = bearish)
    wr = float(ind.get("williams_r") or -50)
    _add("Williams %R", 0.5, -50 < wr < -20, -80 < wr < -50, f"{wr:.0f}")

    alignment = (total_signed / total_weight) if total_weight > 0 else 0.0
    alignment = max(-1.0, min(1.0, alignment))

    # ── C. Combine: aligned signals can boost up to +40%, opposing −40%
    multiplier = 1.0 + 0.4 * alignment
    p_signal = p_base * multiplier

    # ── D. Per-stock historical calibration (blend 30% if known) ────
    if hist_hit_rate is not None and 0 < hist_hit_rate <= 100:
        hist_p = hist_hit_rate / 100.0
        p_final = 0.7 * p_signal + 0.3 * hist_p
        method = (f"vol-base {p_base*100:.0f}% × align {multiplier:.2f}x "
                  f"→ blend hist {hist_hit_rate:.0f}%")
    else:
        p_final = p_signal
        method = f"vol-base {p_base*100:.0f}% × align {multiplier:.2f}x"

    p_final = max(5.0, min(95.0, p_final * 100))

    # Sort breakdown by absolute contribution so the most influential
    # indicators show first in the UI.
    breakdown.sort(key=lambda r: abs(r["contrib"]), reverse=True)

    return {
        "prob_pct": round(p_final, 1),
        "base_pct": round(p_base * 100, 1),
        "alignment": round(alignment, 3),
        "alignment_pct_boost": round((multiplier - 1.0) * 100, 1),
        "breakdown": breakdown,
        "method": method,
        "days": days,
    }


# ─────────────────────────────────────────────────────────────────────────────
# JUDGE AGENT  (fires at 6/9 consensus = 67%)
# ─────────────────────────────────────────────────────────────────────────────
class JudgeAgent:
    name = "Judge Agent"
    emoji = "⚖️"
    THRESHOLD = 5  # out of 9 analysts

    def decide(self, votes: list, ind: dict) -> dict:
        price = ind.get("price", 0)
        atr = ind.get("atr14", price * 0.02) if price else 1

        call_count = sum(1 for v in votes if v["vote"] == "BUY_CALL")
        put_count = sum(1 for v in votes if v["vote"] == "BUY_PUT")
        hold_count = sum(1 for v in votes if v["vote"] == "HOLD")
        total_analysts = len(votes)

        risk = next((v for v in votes if v["agent"] == "Risk Agent"), {})

        # Pull overextension indicators for the "don't chase tops/bottoms" filter
        rsi = float(ind.get("rsi14") or 50)
        bb_upper = float(ind.get("bb_upper") or price * 1.05)
        bb_lower = float(ind.get("bb_lower") or price * 0.95)
        bb_mid = float(ind.get("bb_mid") or price)
        bb_width = bb_upper - bb_lower
        bb_z = ((price - bb_mid) / (bb_width / 2)) if bb_width > 0 else 0.0  # -1..+1 inside band, >1 outside upper

        # Risk/reward sized to volatility regime: tight ATR (low-vol stocks like SPY)
        # need wider stops + closer targets so they don't whipsaw.
        atr_pct_now = (atr / price * 100) if price else 2.0
        if atr_pct_now < 1.5:           # low vol (e.g. SPY, large indexes)
            stop_mult, tgt_mult = 1.4, 1.0
        elif atr_pct_now > 4.0:         # high vol (e.g. TSLA, NVDA in news)
            stop_mult, tgt_mult = 0.9, 1.6
        else:                            # normal
            stop_mult, tgt_mult = 1.1, 1.3

        if call_count >= self.THRESHOLD:
            signal = "BUY_CALL"
            agreed = [v["agent"] for v in votes if v["vote"] == "BUY_CALL"]
            disagreed = [v["agent"] for v in votes if v["vote"] != "BUY_CALL"]
            conf = float(np.mean([v["confidence"] for v in votes if v["vote"] == "BUY_CALL"]))
            entry = price
            stop = round(price - stop_mult * atr, 2)
            target = round(price + tgt_mult * atr, 2)
        elif put_count >= self.THRESHOLD:
            signal = "BUY_PUT"
            agreed = [v["agent"] for v in votes if v["vote"] == "BUY_PUT"]
            disagreed = [v["agent"] for v in votes if v["vote"] != "BUY_PUT"]
            conf = float(np.mean([v["confidence"] for v in votes if v["vote"] == "BUY_PUT"]))
            entry = price
            stop = round(price + stop_mult * atr, 2)
            target = round(price - tgt_mult * atr, 2)
        else:
            signal = "HOLD"
            agreed = []
            disagreed = []
            conf = float(np.mean([v["confidence"] for v in votes])) if votes else 50
            entry = price
            stop = round(price - stop_mult * atr, 2)
            target = price

        # ── Overextension VETO ("don't chase") ──────────────────────────
        # Back-testing showed the agents pile onto strong trends and buy
        # right at exhaustion points. Veto when price is over-extended.
        veto_reason = None
        if signal == "BUY_CALL":
            # OR condition (not AND) — either extreme overbought reading vetos
            if rsi >= 72 or bb_z >= 0.85 or price >= bb_upper:
                signal = "HOLD"
                target = price
                stop = round(price - stop_mult * atr, 2)
                conf = 50.0
                veto_reason = f"overbought (RSI {rsi:.0f}, BB-z {bb_z:+.2f}) — chasing top vetoed"
            elif rsi >= 65 or bb_z >= 0.6:
                conf *= 0.80  # mildly extended → trim
        elif signal == "BUY_PUT":
            if rsi <= 28 or bb_z <= -0.85 or price <= bb_lower:
                signal = "HOLD"
                target = price
                stop = round(price + stop_mult * atr, 2)
                conf = 50.0
                veto_reason = f"oversold (RSI {rsi:.0f}, BB-z {bb_z:+.2f}) — chasing bottom vetoed"
            elif rsi <= 35 or bb_z <= -0.6:
                conf *= 0.80

        # ── Accuracy-booster filters (run BEFORE the evidence-pillar gate) ─
        # These three filters all come from well-documented edge sources:
        #   1. CHOP filter      – ADX<18 means non-trending → all signals are noise
        #   2. WEEKLY trend     – Higher-timeframe trend filter (weekly EMA20)
        #   3. INDEX context    – Don't fight SPY's macro direction
        adx = float(ind.get("adx") or 20)
        weekly = ind.get("weekly_trend") or {"dir": "flat", "strength": 0.0}
        spy = ind.get("spy_trend") or {"dir": "flat", "pct_from_ema50": 0.0}

        # 1) Chop filter — ADX measures TREND STRENGTH. <14 = extreme chop only.
        #    (Was <18; loosened so normal mildly-trending stocks can still fire.)
        if signal != "HOLD" and adx < 14:
            evidence_reason = f"ADX {adx:.0f} < 14 — extreme chop, no trend to ride"
            signal = "HOLD"
            target = price
            stop = round(price - stop_mult * atr, 2)
            conf = 50.0
        elif signal != "HOLD" and adx < 18:
            # Mild chop — keep signal but trim confidence
            conf *= 0.85

        # 2) Weekly counter-trend filter — only veto when weekly trend is
        #    clearly strong against the daily call (>1.5%/wk slope).
        #    Mild counter-trend (0.3-1.5%) just trims confidence.
        wstr = float(weekly.get("strength", 0) or 0)
        if signal == "BUY_CALL" and weekly.get("dir") == "down":
            if wstr > 1.5:
                evidence_reason = f"weekly trend strongly down ({wstr:.1f}%/wk) — daily CALL fights higher TF"
                signal = "HOLD"
                target = price
                stop = round(price - stop_mult * atr, 2)
                conf = 50.0
            elif wstr > 0.4:
                conf *= 0.85
        elif signal == "BUY_PUT" and weekly.get("dir") == "up":
            if wstr > 1.5:
                evidence_reason = f"weekly trend strongly up ({wstr:.1f}%/wk) — daily PUT fights higher TF"
                signal = "HOLD"
                target = price
                stop = round(price - stop_mult * atr, 2)
                conf = 50.0
            elif wstr > 0.4:
                conf *= 0.85

        # 3) SPY context — fighting the index is allowed but penalised.
        if signal != "HOLD" and spy.get("dir") not in ("flat", "self"):
            if (signal == "BUY_CALL" and spy["dir"] == "down") or \
               (signal == "BUY_PUT" and spy["dir"] == "up"):
                conf *= 0.88   # 12% confidence haircut for fighting the index

        # ── Evidence-pillar gate ("don't fire with nothing backing it") ─
        # Count how many INDEPENDENT lines of evidence actually agree with
        # the chosen direction. Four pillars, each weighted equally:
        #   1. TREND     – SuperTrend direction + EMA9 vs EMA21
        #   2. MOMENTUM  – MACD histogram + ROC10 + ADX directional bias
        #   3. VOLUME    – OBV slope + 5-vs-20-day volume trend
        #   4. PRICE     – position vs VWAP + last candle vs prior close
        # Need >=3 pillars aligned for full confidence, =2 trims confidence,
        # <2 means the agents are voting on flimsy evidence -> HOLD.
        evidence_reason = None
        evidence_pillars: dict = {}
        if signal != "HOLD":
            ema9 = float(ind.get("ema9") or price)
            ema21 = float(ind.get("ema21") or price)
            st_dir = ind.get("supertrend_dir", "up")
            macd_hist = float(ind.get("macd_hist") or 0)
            roc10 = float(ind.get("change_5d") or 0)  # 5-day price change % (proxy for ROC)
            plus_di = float(ind.get("plus_di") or 25)
            minus_di = float(ind.get("minus_di") or 25)
            obv_slope = float(ind.get("obv_slope_10d_pct") or 0)
            vol_trend = float(ind.get("vol_trend_5v20") or 1.0)
            pvwap = float(ind.get("price_vs_vwap_pct") or 0)
            change_1d = float(ind.get("change_1d") or 0)

            # Soft per-pillar scoring (0..1) — partial agreement still counts.
            # Pillar "confirms" at score >= 0.5. This avoids the binary
            # "all-or-nothing" trap that was killing too many legit signals.
            if signal == "BUY_CALL":
                trend_score = 0.5 * (st_dir == "up") + 0.5 * (ema9 > ema21)
                momo_score = (0.34 * (macd_hist > 0)
                              + 0.33 * (roc10 > 0)
                              + 0.33 * (plus_di >= minus_di))
                vol_score = 0.5 * (obv_slope > 0) + 0.5 * (vol_trend >= 0.9)
                price_score = 0.5 * (pvwap > 0) + 0.5 * (change_1d >= 0)
            else:  # BUY_PUT
                trend_score = 0.5 * (st_dir == "down") + 0.5 * (ema9 < ema21)
                momo_score = (0.34 * (macd_hist < 0)
                              + 0.33 * (roc10 < 0)
                              + 0.33 * (minus_di >= plus_di))
                vol_score = 0.5 * (obv_slope < 0) + 0.5 * (vol_trend >= 0.9)
                price_score = 0.5 * (pvwap < 0) + 0.5 * (change_1d <= 0)

            trend_ok = trend_score >= 0.5
            momo_ok = momo_score >= 0.5
            vol_ok = vol_score >= 0.5
            price_ok = price_score >= 0.5

            pillars_aligned = sum([trend_ok, momo_ok, vol_ok, price_ok])
            total_pillar_score = trend_score + momo_score + vol_score + price_score  # 0..4
            pillar_names = ["trend", "momentum", "volume", "price"]
            agreed_pillars = [n for n, ok in zip(pillar_names, [trend_ok, momo_ok, vol_ok, price_ok]) if ok]

            evidence_pillars = {
                "trend": bool(trend_ok),
                "momentum": bool(momo_ok),
                "volume": bool(vol_ok),
                "price": bool(price_ok),
                "aligned": pillars_aligned,
                "total": 4,
                "score": round(total_pillar_score, 2),
            }

            # Veto only when the underlying tape is BARELY supportive
            # (total score below 1.0 out of 4 = essentially nothing backing it).
            if total_pillar_score < 1.0:
                evidence_reason = (
                    f"pillar score {total_pillar_score:.1f}/4.0 "
                    f"({', '.join(agreed_pillars) or 'none confirm'}) — too weak"
                )
                signal = "HOLD"
                target = price
                stop = round(price - stop_mult * atr, 2)
                conf = 50.0
            elif total_pillar_score < 2.0:
                conf *= 0.78  # weak (1.0-2.0)
            elif total_pillar_score < 3.0:
                conf *= 0.92  # moderate (2.0-3.0)
            # 3.0+ → full confidence (well-supported)

        # Consensus strength: the more dissenting agents, the lower the conviction.
        # 9/9 agree → 1.00x; 5/9 → 0.75x.
        if signal != "HOLD" and total_analysts > 0:
            agree_n = call_count if signal == "BUY_CALL" else put_count
            consensus_factor = 0.55 + 0.45 * (agree_n / total_analysts)
            conf *= consensus_factor

        conf = max(40.0, min(95.0, conf))

        direction = "BULLISH" if signal == "BUY_CALL" else "BEARISH" if signal == "BUY_PUT" else "NEUTRAL"
        opts = suggest_options(direction, price, atr, ind)

        # ── Forecast line ────────────────────────────────────────────────
        # 1. Anchor first point at NOW + current price so the line visually connects to the live chart
        # 2. Project toward the target with magnitude scaled by confidence:
        #    high conviction → the line reaches the target; low conviction → it falls short
        # 3. Use real trading days (Mon–Fri) for the next 7 sessions
        from datetime import datetime, timedelta, timezone
        forecast = []
        now_ts = int(time.time())
        if signal != "HOLD":
            # Anchor: forecast starts AT current price/now so it joins the chart's last candle
            forecast.append({"time": now_ts, "value": round(price, 2)})

            # Generate next 7 trading-day timestamps after now
            dt = datetime.fromtimestamp(now_ts, tz=timezone.utc)
            trading_days: list[int] = []
            while len(trading_days) < 7:
                dt += timedelta(days=1)
                if dt.weekday() < 5:  # Mon–Fri only
                    trading_days.append(int(dt.timestamp()))

            # Confidence scales how far the projection actually reaches.
            # 50% conf → 50% of the way to target; 95% conf → 95% of the way.
            conf_scale = max(0.30, min(0.95, conf / 100.0))
            full_move = abs(target - price)
            max_move = full_move * conf_scale

            for i, ts in enumerate(trading_days):
                progress = (i + 1) / 7
                ease = progress * progress * (3 - 2 * progress)  # smooth S-curve
                delta = max_move * ease
                if signal == "BUY_CALL":
                    proj = min(price + delta, target)
                else:
                    proj = max(price - delta, target)
                forecast.append({"time": ts, "value": round(proj, 2)})

        vola = ind.get("volatility_20d", 25)
        pos_size = max(1, 5 - int(vola / 15))

        # Regime-aware Kelly criterion sizing (uses back-test stats per vol regime)
        kelly = compute_position_size(
            signal=signal, confidence=conf, entry=entry, target=target, stop=stop,
            atr_pct=atr_pct_now,
        )

        # Per-stock historical track record — keeps confidence calibrated to reality.
        # Discovered in back-test that the model's hit rate varies WIDELY by symbol
        # (META 80%, MSFT 70%, NVDA 12.5%) and that high-confidence trades aren't
        # any more accurate than low-confidence ones. Show users the truth.
        track_record = get_track_record(ind.get("_symbol", ""))

        # ── REAL TARGET-HIT PROBABILITY ─────────────────────────────────
        # Replace the old "average of agent votes" confidence with the actual
        # probability that price will touch the target inside the forecast
        # window. Uses volatility math (Brownian first-passage) + directional
        # alignment of SuperTrend, EMA, MACD, RSI, BB, Volume, OBV, ADX,
        # Williams %R, Ichimoku, VWAP, Pivot bias, Stochastic, multi-TF trend
        # + per-stock historical hit-rate calibration.
        hit = compute_target_hit_probability(
            signal=signal, price=price, target=target, atr=atr, ind=ind,
            days=7, hist_hit_rate=track_record["hit_rate"] if track_record else None,
        )

        # The headline confidence number IS the real target-hit probability now.
        # Kelly sizer downstream gets a true probability instead of a vote average.
        # Keep the old vote-consensus score as a separate field for transparency.
        vote_consensus = round(conf, 1)
        conf = hit["prob_pct"]

        # If the model has historically been WORSE than coin-flip on this stock,
        # cap reported confidence — refusing to overstate conviction is honest.
        if track_record and track_record["rating"] in ("weak", "poor") and signal != "HOLD":
            conf = min(conf, 55.0)

        # Get Fear & Greed from cache if available
        fg_score = FearGreedAgent._cache.get("score", 50) if FearGreedAgent._cache else 50
        fg_label = FearGreedAgent._cache.get("label", "Unknown") if FearGreedAgent._cache else "Unknown"

        return {
            "signal": signal,
            "confidence": round(conf, 1),
            "target_hit_prob": round(conf, 1),         # alias for clarity in UI
            "target_hit_base_pct": hit["base_pct"],    # vol-only baseline
            "target_hit_alignment": hit["alignment"],  # -1..+1 indicator agreement
            "target_hit_boost_pct": hit["alignment_pct_boost"],
            "target_hit_breakdown": hit["breakdown"],  # per-indicator contribution
            "target_hit_method": hit["method"],
            "target_hit_days": hit["days"],
            "vote_consensus_pct": vote_consensus,      # the old number, for transparency
            "entry_price": round(entry, 2),
            "stop_loss": round(stop, 2),
            "target_price": round(target, 2),
            "agreed_agents": agreed,
            "disagreed_agents": disagreed,
            "vote_tally": {"BUY_CALL": call_count, "BUY_PUT": put_count, "HOLD": hold_count},
            "position_size_pct": pos_size,
            "kelly": kelly,
            "track_record": track_record,
            "judge_reason": (
                f"{call_count}/{total_analysts} CALL, {put_count}/{total_analysts} PUT — " +
                (f"🛑 VETO: {veto_reason}" if veto_reason
                 else (f"🛑 NO BACKING: {evidence_reason}" if evidence_reason
                       else ("✅ CONSENSUS" if signal != "HOLD"
                             else f"⏳ Need {self.THRESHOLD}/{total_analysts}")))
            ),
            "evidence_reason": evidence_reason,
            "evidence_pillars": evidence_pillars or None,
            "macro_context": {
                "adx": round(adx, 1),
                "weekly_trend": weekly,
                "spy_trend": spy,
            },
            "action": opts["action"],
            "strike_hint": opts["strike_hint"],
            "expiry_hint": opts["expiry_hint"],
            "expiry_weekly": opts.get("expiry_weekly", ""),
            "expiry_biweekly": opts.get("expiry_biweekly", ""),
            "expiry_monthly": opts.get("expiry_monthly", ""),
            "entry_trigger": opts["entry_trigger"],
            "risk_note": opts["risk_note"],
            "forecast_line": forecast,
            "fear_greed_score": fg_score,
            "fear_greed_label": fg_label,
        }
