@echo off
REM ────────────────────────────────────────────────────────────────────────────
REM  Run ONCE on your local Windows machine to stop tracking the data files
REM  in git. After this, predictions.db / track_record.json / regime_stats.json
REM  stay local and survive `git pull` without merge conflicts.
REM
REM  The server auto-regenerates track_record.json + regime_stats.json on first
REM  startup (and every 7 days after) via auto_refresh.py. predictions.db is
REM  built up live as the model makes calls.
REM ────────────────────────────────────────────────────────────────────────────

cd /d "%~dp0..\..\.."

echo Removing data files from git tracking (files stay on disk)...
git rm --cached artifacts/api-server/trading/predictions.db 2>nul
git rm --cached artifacts/api-server/trading/track_record.json 2>nul
git rm --cached artifacts/api-server/trading/regime_stats.json 2>nul

echo.
echo Committing the untrack + the new .gitignore entries...
git add .gitignore
git commit -m "Stop tracking local-only data files (auto-regenerated by server)"

echo.
echo Pushing to remote...
git push

echo.
echo Done. From now on, `git pull` will not touch your local data files.
pause
